apiVersion: apps/v1
kind: DaemonSet
metadata:
     name: my-daemonset
spec: 
   template:
     metadata:
       labels:
          app: student-app
   spec: 
      containers:
          - name: my-app
            image: nginx
            ports:
               - name: http
                 protocol: TCP
                 containerport: 80
   selector: 
      matchLabels:
            app: student-app                        