apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels: 
    app: myhttpd
spec:
 containers:
   - name: my-pod-container
     image: nginx:latest
     ports:
      - name: httpd
        containerPort: 80
        protocol: TCP
   - name: secound-container
     image: tomcat  
     ports: 
        - name: java
          container: 8080
          protocol: TCP