apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels: 
    app: myhttpd
spec:
 containers:
   - name: my-pod
     image: nginx:latest
     ports:
      - name: httpd
        containerPort: 80
        protocol: TCP
   - name: my-pod2
     image: tomcat  
     ports: 
      - name: java
        containerPort: 8080
        protocol: TCP